services:
  restapi:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - MINIO_HOST=minio
    ports:
      - "8001:8000"
    networks:
      - fremux_net

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fremux_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    command: server --console-address ":9005" /data
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9005:9005"
    volumes:
      - minio_data:/data
    networks:
      - fremux_net

volumes:
  postgres_data:
  minio_data:

networks:
  fremux_net:
    external: true